[[users]]
username = ""
password = ""
alias = ""
access_key = ""
cookie = ""
csrf = ""
uid = ""
refresh_token = ""
manage_room = []
danmu_length = 30 # 弹幕长度
# 定时循环发送, 在alerts内循环
alerts = []
# 循环时间间隔,开播才发广告
alert_second = 300
# 礼物连送等待
gift_comb_delay = 5
# 送礼感谢格式
gift_thx_format = "感谢{username}投喂的{giftname}x{num}"
sliver_gift_thx_format = "感谢{username}投喂的{giftname}x{num}"
gold_gift_thx_format = "感谢{username}投喂的{giftname}x{num}!"
# 关注感谢格式
focus_thx_format = "谢谢{username}的关注"
# 上船感谢
guard_thx_format = "感谢{username}投喂的{giftname}x{num}"
# 是否仅开播时答谢
only_live_thx = false
# 新关注判定延迟
fans_check_delay = 30

# 粉丝勋章升级提醒
medal_update_format = "恭喜{username}的牌牌升到LV{new_level}!"
# 粉丝勋章检测延迟
medal_update_check_delay = 60
# 随机替换列表，使用标识符可以作为变量取其中的随机值
# 变量名称为{random1} {random2} {ramdom3}
# 举个例子
# random_list_1 = ["小电视","节奏风暴"]
# gift_thx_format = "谢谢{username}投喂的{num}个{giftname}, 浅浅还想吃许多{random1}"

random_list_1 = []
random_list_2 = []
random_list_3 = []

height = 0
weight = 0
# 关键词回复
[[users.reply]]
  key = "^.*(好听).*$"
  percent = 1
  reply = "好听赶紧关注啊！"

# 关键词禁言
[[users.ban]]
  key = "^(好菜)$"
  percent = 1
  hour = 720
